# Generated by Django 5.1.9 on 2026-07-27 22:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlagiarismAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Terminée'), ('failed', 'Échouée')], default='pending', max_length=10)),
                ('overall_score', models.FloatField(default=0.0)),
                ('direct_copy_score', models.FloatField(default=0.0)),
                ('paraphrase_score', models.FloatField(default=0.0)),
                ('cross_lingual_score', models.FloatField(default=0.0)),
                ('structural_score', models.FloatField(default=0.0)),
                ('segments_analyzed', models.PositiveIntegerField(default=0)),
                ('matches_found', models.PositiveIntegerField(default=0)),
                ('processing_time', models.FloatField(default=0.0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='documents.document')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'plagiarism_analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlagiarismMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_type', models.CharField(choices=[('direct', 'Copie directe'), ('paraphrase', 'Paraphrase'), ('cross_lingual', 'Cross-lingue'), ('structural', 'Structurelle')], max_length=15)),
                ('similarity_score', models.FloatField()),
                ('source_text', models.TextField()),
                ('source_char_start', models.PositiveIntegerField(default=0)),
                ('source_char_end', models.PositiveIntegerField(default=0)),
                ('target_text', models.TextField()),
                ('target_document_title', models.CharField(blank=True, max_length=500)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='detection.plagiarismanalysis')),
                ('source_segment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_matches', to='documents.documentsegment')),
                ('target_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_matches', to='documents.documentsegment')),
            ],
            options={
                'db_table': 'plagiarism_matches',
                'ordering': ['-similarity_score'],
            },
        ),
    ]
