FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN python -m spacy download fr_core_news_lg

COPY backend/ .

RUN mkdir -p /app/media/uploads /app/faiss_indexes

CMD ["celery", "-A", "plagiat_project", "worker", "--loglevel=info", "--concurrency=2", "--max-tasks-per-child=50"]
