# Generated by Django 5.1.9 on 2026-07-27 22:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX')], max_length=4)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('uploaded', 'Téléversé'), ('processing', 'En traitement'), ('processed', 'Traité'), ('error', 'Erreur')], default='uploaded', max_length=12)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(default='fr', max_length=10)),
                ('raw_text', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('chapter', 'Chapitre'), ('section', 'Section'), ('paragraph', 'Paragraphe'), ('sentence', 'Phrase')], max_length=10)),
                ('position', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('clean_text', models.TextField(blank=True)),
                ('char_start', models.PositiveIntegerField(default=0)),
                ('char_end', models.PositiveIntegerField(default=0)),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('embedding_model', models.CharField(blank=True, max_length=100)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='documents.document')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.documentsegment')),
            ],
            options={
                'db_table': 'document_segments',
                'ordering': ['document', 'position'],
                'indexes': [models.Index(fields=['document', 'level'], name='document_se_documen_9ea3e4_idx'), models.Index(fields=['document', 'position'], name='document_se_documen_717fa8_idx')],
            },
        ),
    ]
